services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: voho_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/pg/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d voho_saas"]
      interval: 5s
      timeout: 5s
      retries: 15

volumes:
  db_data:
