version: "3.9"

services:
  db:
    image: postgres:16
    container_name: voho_db
    environment:
      POSTGRES_DB: voho_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/pg/init:/docker-entrypoint-initdb.d  # enables pgcrypto on first run
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d voho_saas"]
      interval: 5s
      timeout: 5s
      retries: 15

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: voho_api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/voho_saas
      JWT_SECRET: change-me
      # set if you’ll hit the API from a browser/app
      CORS_ORIGIN: http://localhost
      # Ultravox can stay mocked for test
      ULTRAVOX_API_URL: https://api.ultravox.ai
      ULTRAVOX_API_KEY: dummy
      ULTRAVOX_MOCK: "true"
      BASE_DOMAIN: lvh.me
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    # mount code only if you want hot-reload in dev:
    # volumes:
    #   - ./server:/app

  # Optional DB UI
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: voho_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
